In [ ]:
# ! pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\dixit\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\dixit\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/10.0 MB 6.3 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/10.0 MB 4.8 MB/s eta 0:00:02
   ---------- ----------------------------- 2.6/10.0 MB 4.4 MB/s eta 0:00:02
   ------------- -------------------------- 3.4/10.0 MB 4.3 MB/s eta 0:00:02
   ---------------- ----------------------- 4.2/10.0 MB 4.2 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/10.0 MB 4.1 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/10.0 MB 4.1 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/10.0 MB 4.1 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/10.0 MB 4.1 MB/s eta 0:00:01
   --------------------------------- ------ 8.4/10.0 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 9.2/10.0 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 3.9 MB/s  0:00:02
Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.6 MB 4.5 MB/s eta 0:00:03
   ----- ---------------------------------- 1.8/12.6 MB 4.2 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.6 MB 4.1 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.6 MB 4.0 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 4.0 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.6 MB 4.0 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.6 MB 4.0 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.6 MB 4.0 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.6 MB 3.9 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.6 MB 3.9 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 3.9 MB/s  0:00:03
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.1 pandas-3.0.5 tzdata-2026.3

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\dixit\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import seaborn as sns
import pandas as pd

In [8]:
df= pd.DataFrame({"Age":[20,25,30,35,40], "Salary":[20000,30000,40000,50000,60000]})

In [9]:
df

   Age  Salary
0   20   20000
1   25   30000
2   30   40000
3   35   50000
4   40   60000

In [10]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   30.000000  40000.000000
std     7.905694  15811.388301
min    20.000000  20000.000000
25%    25.000000  30000.000000
50%    30.000000  40000.000000
75%    35.000000  50000.000000
max    40.000000  60000.000000

In [ ]:
X = np.array((df.Age)).reshape(5,1)
Y = np.array((df.Salary)).reshape(5,1)

In [33]:
from sklearn.model_selection import train_test_split


X_Train, X_Test, Y_Train, Y_Test=train_test_split(X,Y, test_size=0.2)

In [34]:
import numpy as np
X_Train=np.array((X_Train))
X_Test=np.array((X_Test))
Y_Train=np.array((Y_Train))
Y_Test=np.array((Y_Test))

In [24]:
X_Train.shape

(4,)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_Train_scaler= scaler.fit_transform(X_Train, y = None)
y_Train_scaler= scaler.fit_transform(Y_Train, y = None)
x_Test_scaler= scaler.transform(X_Test)
y_Test_scaler= scaler.transform(Y_Test)

In [45]:
print(x_Train_scaler.mean())
print(x_Train_scaler.std())

0.0
1.0

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()
X_Train_Scaler = scalar.fit_transform(X_Train)
X_Test_Scaler = scalar.transform(X_Test)
Y_Train_Scaler = scalar.fit_transform(Y_Train)
Y_Train_Scaler = scalar.transform(Y_Test)

In [44]:
print(X_Train_Scaler.mean())
print(X_Train_Scaler.std())

0.5625
0.369754986443726